name: future_sales
channels:
  - defaults
dependencies:
  - pip=20.2.2
  - python=3.8.5
  - pip:
      - numpy==1.19.1
      - pandas==1.1.1
      - scikit-learn==0.23.2
      - tensorflow==2.3.0
      - matplotlib
      - seaborn
      - scipy
      - statsmodels
      - fbprophet


